language: python
python:
  - "3.5"
before_script:
  - pip install --upgrade pip
install:
  - pip install codecov
  - make build
  - pip install -r test_requirements.txt
script:
  - make test
after_success:
  - codecov
