language: python
python:
  - "3.5"
before_script:
  - pip install --upgrade pip
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
script:
  - make test
  - coverage run -m unittest tests/*.py
